### ISSUE TITLE
Migration Problem

### ISSUE THREAD

**Issue by juancwu** [LaurierCS/CodingJourney#33]
```shell
Operations to perform:
  Apply all migrations: admin, app, auth, contenttypes, sessions
Running migrations:
  Applying app.0002_remove_project_difficulty...Traceback (most recent call last):
  File "/root/pod/manage.py", line 22, in <module>
    main()
  File "/root/pod/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/db/migrations/migration.py", line 114, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/root/.local/share/virtualenvs/pod-tTMt1Z3T/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 157, in state_forwards
    model_state = state.models[app_label, self.model_name_lower]
KeyError: ('app', 'project')
```

# Reproduce
run migration command in shell with main branch latest updates.
`python manage.py migrate`

**Comment by teoh4770** [comment]
i didn't, everything works fine though
